yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
NUM_OF_SYM = 15


class Group(models.Model):
    title = models.CharField(
        'Название',
        max_length=200,
        help_text='Название группы'
    )
    slug = models.SlugField(
        'Адрес',
        unique=True,
        help_text='Адрес группы',
    )
    description = models.TextField(
        'Описание',
        help_text='Описание группы'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст',
        help_text='Текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:NUM_OF_SYM]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        'Текст',
        help_text='Текст комментария',
    )
    created = models.DateTimeField(
        'Дата',
        auto_now_add=True,
    )

    def __str__(self):
        return self.text[:NUM_OF_SYM]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        null=True,
    )

    def __str__(self):
        return self.author.username

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа поста'
        }
        help_texts = {
            'text': 'Введите текст поста',
            'group': 'Выберите группу поста (необязательно)'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Введите текст комментария',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm

NUM_OF_POSTS = 10


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = request.user
    profile = get_object_or_404(User, username=username)
    posts = profile.posts.all()
    number = posts.count()
    paginator = Paginator(posts, NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=profile
    ).exists()
    context = {
        'profile': profile,
        'posts': posts,
        'number': number,
        'page_obj': page_obj,
        'following': following,
        'user': user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    author = post_detail.author
    edit = False
    if author == request.user:
        edit = True
    number = author.posts.all().count()
    form = CommentForm(request.POST or None)
    comments = post_detail.comments.all()
    context = {
        'post_detail': post_detail,
        'number': number,
        'comments': comments,
        'form': form,
        'edit': edit,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'is_edit': is_edit,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    empty = False
    if not posts:
        empty = True
    paginator = Paginator(posts, NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'empty': empty,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Новый пост
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" action="" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                {% if is_edit %}
                  <button type="submit" class="btn btn-primary">
                    Сохранить
                  </button>
                {% else %}
                  <button type="submit" class="btn btn-primary">
                    Добавить
                  </button>
                {% endif %}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Подписка
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% if empty %}
    Подписок еще нет!
  {% endif %}
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: 
            {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
            {% else %}
              {{ post.author }}
            {% endif %}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </article>  
    {% if post.group is not NULL %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article> 
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </article>  
    {% if post.group is not NULL %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>{% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: 
            {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
            {% else %}
              {{ post.author }}
            {% endif %}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </article>  
    {% if post.group is not NULL %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  {{ post_detail.text|truncatechars:30 }} 
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post_detail.pub_date|date:"d E Y" }} 
        </li>
        {% if post_detail.group is not NULL %}
          <li class="list-group-item">
            Группа: {{ post_detail.group }}
              <a href="{% url 'posts:group_list' post_detail.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
          <li class="list-group-item">
            Автор: 
            {% if post_detail.author.get_full_name %}
              {{ post_detail.author.get_full_name }}
            {% else %}
              {{ post_detail.author }}
            {% endif %}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ number }}</span>
          </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_detail.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_detail.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post_detail.text }}   
      </p>
      {% if edit %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_detail.pk %}">
          редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post_detail.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %} 
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ profile.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ profile.get_full_name }}
    <h3>Всего постов: {{ number }} </h3>
    {% if user != profile %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' profile.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' profile.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text  }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </article>       
      {% if post.group is not NULL %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}       
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}   
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}